node{
    stage('Cloning Repository') {
        git 'https://github.com/cit-agnitio/student-springboot.git'
        sh 'env'
    }

    stage('Compile Code') {
        try {
            withMaven(jdk: 'JDK8', maven: 'MAVEN354') {
                sh 'mvnx compile'
            }
        }
        catch (exc) {
            slackSend color: '#FF0000', message: "Jenkins Job FAILURE\nJenkins Job NAME: ${env.JOB_NAME}\nJenkins Job URL: ${env.BUILD_URL}"
            sh 'false'
        }
    }

    stage('Code Analysis') {
        echo "Code Analysis with Sonar"
    }
}
