node{
    stage('Cloning Repository') {
        git 'https://github.com/cit-agnitio/student-springboot.git'
        sh 'env'
    }

    stage('Compile Code') {
        try {
            withMaven(jdk: 'JDK8', maven: 'MAVEN354') {
                sh 'mvnx compile'
            }
        }
        catch (exc) {
            slackSend "Jenkins Job ia a failure\nNew Line"
            sh 'false'
        }
    }

    stage('Code Analysis') {
        echo "Code Analysis with Sonar"
    }
}
